version: '3.9'

services:
  build_image:
    build: .
    image: service/payment # use your own image name e.g. rancher/my-app:{VERSION}
  app_svc:
    container_name: payment-service
    image: service/payment
    depends_on: [build_image]
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DB=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
      - STORE_ID=$STORE_ID
      - STORE_PASSWORD=$STORE_PASSWORD
      - API_BASE_URL=$API_BASE_URL
    ports:
      - 8082:8082
    networks:
      - svc-network
networks:
  svc-network:
    driver: bridge

volumes:
  dbdata:
