version: '3.9'

services:
  build_image:
    build: .
    image: services/sns:${VERSION} # use your own image name e.g. rancher/my-app:{VERSION}
  app_svc:
    container_name: sns-service
    image: services/sns:${VERSION}
    depends_on: [build_image]
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - 8282:8282
    networks:
      - svc-network
    command: scripts/wait-for.sh mongo:27017 -- bash scripts/startup.sh
  
  mongo:
    container_name: mongo
    image: mongo:4.1.8-xenial
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    ports:
      - 27020:27017
    volumes:
      - dbdata:/data/db
    networks:
      - svc-network

networks:
  svc-network:
    driver: bridge

volumes:
  dbdata: