version: '3.9'

# If you want to use mysql instead of mongodb, please move the entire mysql
# block from below under `services`. You should then uncomment the
# mysql related env vars in app_svc environment section. Do not forget
# to uncomment mysql-data under volumes.
x-disabled:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=payment_db
      # Uncomment following line, if root user does not have a
      # password. And remove MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      #- MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PWORD
      # Uncomment next lines if you have a different user
      # than root.
      # - MYSQL_USER=$MYSQL_USER
      # - MYSQL_PASSWORD=$MYSQL_PWORD
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - svc-network

services:
  build_image:
    build: .
    image: services/payment-service:1.0.0 # use your own image name e.g. rancher/my-app:{VERSION}
  
  app_svc:
    container_name: payment-service
    image: payment-service:1.0.0
    depends_on: [build_image]
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DB=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_PORT=$MYSQL_PORT
      - STORE_ID=$STORE_ID
      - STORE_PASSWORD=$STORE_PASSWORD
      - API_BASE_URL=$API_BASE_URL
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    ports:
      - 8082:8082
    networks:
      - svc-network
    command: scripts/startup.sh
  
  #mongo:
  #  container_name: mongo
  #  image: mongo:4.1.8-xenial
  #  restart: always
  #  environment:
  #    - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #    - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #    - MONGO_INITDB_DATABASE=$DB_NAME
  #  ports:
  #    - $MONGO_HOST_PORT:$MONGO_PORT
  #  volumes:
  #    - mongo-data:/data/db
  #  networks:
  #    - svc-network

networks:
  svc-network:
    driver: bridge

volumes:
  mongo-data:
  mysql-data: # uncomment if using mysql